-- ============================================================
-- SISTEM PERSEDIAAN BAHAN BAKU DAN BARANG JADI TOKO BUTIK
-- PostgreSQL / Supabase
-- ============================================================

-- ============================================================
-- 1. TABEL BAHAN BAKU
-- ============================================================

CREATE TABLE IF NOT EXISTS public.bahan_baku (
    id_bahan BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    kode_bahan VARCHAR(20) NOT NULL UNIQUE,

    nama_bahan VARCHAR(100) NOT NULL,

    jenis_bahan VARCHAR(50),

    satuan VARCHAR(20) NOT NULL,

    stok NUMERIC(12,2) NOT NULL DEFAULT 0,

    stok_minimum NUMERIC(12,2) NOT NULL DEFAULT 0,

    aktif BOOLEAN NOT NULL DEFAULT TRUE,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT bahan_stok_tidak_negatif
        CHECK (stok >= 0),

    CONSTRAINT bahan_stok_minimum_tidak_negatif
        CHECK (stok_minimum >= 0)
);

ALTER TABLE public.bahan_baku
ADD COLUMN IF NOT EXISTS aktif BOOLEAN NOT NULL DEFAULT TRUE;


-- ============================================================
-- 2. TABEL BARANG JADI
-- ============================================================

CREATE TABLE IF NOT EXISTS public.barang_jadi (
    id_barang BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    kode_barang VARCHAR(20) NOT NULL UNIQUE,

    nama_barang VARCHAR(100) NOT NULL,

    kategori VARCHAR(50),

    ukuran VARCHAR(10),

    warna VARCHAR(30),

    harga_jual NUMERIC(15,2) NOT NULL DEFAULT 0,

    stok INTEGER NOT NULL DEFAULT 0,

    aktif BOOLEAN NOT NULL DEFAULT TRUE,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT barang_harga_tidak_negatif
        CHECK (harga_jual >= 0),

    CONSTRAINT barang_stok_tidak_negatif
        CHECK (stok >= 0)
);

ALTER TABLE public.barang_jadi
ADD COLUMN IF NOT EXISTS aktif BOOLEAN NOT NULL DEFAULT TRUE;


-- ============================================================
-- 3. TABEL DETAIL PRODUKSI
--
-- Menentukan bahan apa saja yang diperlukan
-- untuk membuat satu barang jadi.
-- ============================================================

CREATE TABLE IF NOT EXISTS public.detail_produksi (
    id_detail BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    id_barang BIGINT NOT NULL,

    id_bahan BIGINT NOT NULL,

    jumlah_digunakan NUMERIC(12,2) NOT NULL,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_detail_barang
        FOREIGN KEY (id_barang)
        REFERENCES public.barang_jadi(id_barang)
        ON DELETE CASCADE,

    CONSTRAINT fk_detail_bahan
        FOREIGN KEY (id_bahan)
        REFERENCES public.bahan_baku(id_bahan)
        ON DELETE CASCADE,

    CONSTRAINT unique_barang_bahan
        UNIQUE (id_barang, id_bahan),

    CONSTRAINT jumlah_bahan_harus_positif
        CHECK (jumlah_digunakan > 0)
);


-- ============================================================
-- 4. TABEL TRANSAKSI
--
-- Jenis:
-- MASUK     = bahan baku masuk
-- BAHAN_KELUAR = bahan baku keluar untuk pemakaian langsung
-- PRODUKSI  = menghasilkan barang jadi
-- KELUAR    = barang jadi keluar/terjual
-- ============================================================

CREATE TABLE IF NOT EXISTS public.transaksi (
    id_transaksi BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    tanggal DATE NOT NULL DEFAULT CURRENT_DATE,

    jenis_transaksi VARCHAR(20) NOT NULL,

    keterangan TEXT,

    id_bahan BIGINT,

    id_barang BIGINT,

    jumlah NUMERIC(12,2) NOT NULL,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_transaksi_bahan
        FOREIGN KEY (id_bahan)
        REFERENCES public.bahan_baku(id_bahan)
        ON DELETE RESTRICT,

    CONSTRAINT fk_transaksi_barang
        FOREIGN KEY (id_barang)
        REFERENCES public.barang_jadi(id_barang)
        ON DELETE RESTRICT,

    CONSTRAINT jenis_transaksi_valid
        CHECK (
            jenis_transaksi IN (
                'MASUK',
                'BAHAN_KELUAR',
                'PRODUKSI',
                'KELUAR'
            )
        ),

    CONSTRAINT jumlah_transaksi_harus_positif
        CHECK (jumlah > 0),

    CONSTRAINT transaksi_relasi_valid
        CHECK (
            (jenis_transaksi = 'MASUK'
                AND id_bahan IS NOT NULL
                AND id_barang IS NULL)

            OR

            (jenis_transaksi = 'BAHAN_KELUAR'
                AND id_bahan IS NOT NULL
                AND id_barang IS NULL)

            OR

            (jenis_transaksi = 'PRODUKSI'
                AND id_barang IS NOT NULL
                AND id_bahan IS NULL)

            OR

            (jenis_transaksi = 'KELUAR'
                AND id_barang IS NOT NULL
                AND id_bahan IS NULL)
        )
);

ALTER TABLE public.transaksi
DROP CONSTRAINT IF EXISTS jenis_transaksi_valid;

ALTER TABLE public.transaksi
ADD CONSTRAINT jenis_transaksi_valid
CHECK (jenis_transaksi IN ('MASUK', 'BAHAN_KELUAR', 'PRODUKSI', 'KELUAR'));

ALTER TABLE public.transaksi
DROP CONSTRAINT IF EXISTS transaksi_relasi_valid;

ALTER TABLE public.transaksi
ADD CONSTRAINT transaksi_relasi_valid
CHECK (
    (jenis_transaksi IN ('MASUK', 'BAHAN_KELUAR')
        AND id_bahan IS NOT NULL AND id_barang IS NULL)
    OR
    (jenis_transaksi IN ('PRODUKSI', 'KELUAR')
        AND id_barang IS NOT NULL AND id_bahan IS NULL)
);


-- ============================================================
-- INDEX
-- ============================================================

CREATE INDEX IF NOT EXISTS idx_bahan_nama
ON public.bahan_baku(nama_bahan);

CREATE INDEX IF NOT EXISTS idx_barang_nama
ON public.barang_jadi(nama_barang);

CREATE INDEX IF NOT EXISTS idx_transaksi_tanggal
ON public.transaksi(tanggal);

CREATE INDEX IF NOT EXISTS idx_transaksi_jenis
ON public.transaksi(jenis_transaksi);


-- ============================================================
-- FUNCTION:
-- MENGUPDATE STOK SETELAH TRANSAKSI
-- ============================================================

CREATE OR REPLACE FUNCTION public.proses_transaksi_stok()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
    detail RECORD;
    kebutuhan NUMERIC(12,2);
    stok_bahan_saat_ini NUMERIC(12,2);
BEGIN
    IF NEW.jenis_transaksi = 'MASUK' THEN
        UPDATE public.bahan_baku
        SET stok = stok + NEW.jumlah
        WHERE id_bahan = NEW.id_bahan;

        IF NOT FOUND THEN
            RAISE EXCEPTION 'Bahan baku tidak ditemukan';
        END IF;
    ELSIF NEW.jenis_transaksi = 'BAHAN_KELUAR' THEN
        UPDATE public.bahan_baku
        SET stok = stok - NEW.jumlah
        WHERE id_bahan = NEW.id_bahan
          AND stok >= NEW.jumlah;

        IF NOT FOUND THEN
            RAISE EXCEPTION 'Stok bahan baku tidak mencukupi atau bahan tidak ditemukan';
        END IF;
    ELSIF NEW.jenis_transaksi = 'KELUAR' THEN
        IF NEW.jumlah <> TRUNC(NEW.jumlah) THEN
            RAISE EXCEPTION 'Jumlah barang jadi harus bilangan bulat';
        END IF;

        UPDATE public.barang_jadi
        SET stok = stok - NEW.jumlah::INTEGER
        WHERE id_barang = NEW.id_barang
          AND stok >= NEW.jumlah;

        IF NOT FOUND THEN
            RAISE EXCEPTION 'Stok barang jadi tidak mencukupi atau barang tidak ditemukan';
        END IF;
    ELSIF NEW.jenis_transaksi = 'PRODUKSI' THEN
        IF NEW.jumlah <> TRUNC(NEW.jumlah) THEN
            RAISE EXCEPTION 'Jumlah produksi harus bilangan bulat';
        END IF;

        IF NOT EXISTS (
            SELECT 1
            FROM public.detail_produksi
            WHERE id_barang = NEW.id_barang
        ) THEN
            RAISE EXCEPTION 'Resep produksi barang belum dibuat';
        END IF;

        IF EXISTS (
            SELECT 1
            FROM public.detail_produksi AS dp
            JOIN public.bahan_baku AS bb ON bb.id_bahan = dp.id_bahan
            WHERE dp.id_barang = NEW.id_barang
              AND NOT bb.aktif
        ) THEN
            RAISE EXCEPTION 'Resep menggunakan bahan baku yang sudah diarsipkan. Perbarui bahan habis pakai terlebih dahulu.';
        END IF;

        FOR detail IN
            SELECT dp.id_bahan, dp.jumlah_digunakan, bb.nama_bahan
            FROM public.detail_produksi AS dp
            JOIN public.bahan_baku AS bb ON bb.id_bahan = dp.id_bahan
            WHERE dp.id_barang = NEW.id_barang
            ORDER BY dp.id_bahan
        LOOP
            kebutuhan := detail.jumlah_digunakan * NEW.jumlah;

            UPDATE public.bahan_baku
            SET stok = stok - kebutuhan
            WHERE id_bahan = detail.id_bahan
              AND stok >= kebutuhan;

            IF NOT FOUND THEN
                SELECT COALESCE(stok, 0)
                INTO stok_bahan_saat_ini
                FROM public.bahan_baku
                WHERE id_bahan = detail.id_bahan;

                RAISE EXCEPTION
                    'Stok bahan "%" tidak mencukupi. Dibutuhkan: %, tersedia: %',
                    detail.nama_bahan,
                    kebutuhan,
                    COALESCE(stok_bahan_saat_ini, 0);
            END IF;
        END LOOP;

        UPDATE public.barang_jadi
        SET stok = stok + NEW.jumlah::INTEGER
        WHERE id_barang = NEW.id_barang;
    END IF;

    RETURN NEW;
END;
$$;


-- ============================================================
-- TRIGGER
-- ============================================================

DROP TRIGGER IF EXISTS trigger_proses_transaksi_stok ON public.transaksi;

CREATE TRIGGER trigger_proses_transaksi_stok

AFTER INSERT ON public.transaksi

FOR EACH ROW

EXECUTE FUNCTION public.proses_transaksi_stok();


-- ============================================================
-- DATA CONTOH BAHAN BAKU
-- ============================================================

INSERT INTO public.bahan_baku
(
    kode_bahan,
    nama_bahan,
    jenis_bahan,
    satuan,
    stok,
    stok_minimum
)
VALUES

(
    'BB001',
    'Kain Katun',
    'Katun',
    'meter',
    100,
    20
),

(
    'BB002',
    'Kain Denim',
    'Denim',
    'meter',
    50,
    10
),

(
    'BB003',
    'Benang Jahit',
    'Benang',
    'roll',
    30,
    5
),

(
    'BB004',
    'Kancing',
    'Aksesoris',
    'pcs',
    500,
    100
)
ON CONFLICT (kode_bahan) DO NOTHING;


-- ============================================================
-- DATA CONTOH BARANG JADI
-- ============================================================

INSERT INTO public.barang_jadi
(
    kode_barang,
    nama_barang,
    kategori,
    ukuran,
    warna,
    harga_jual,
    stok
)
VALUES

(
    'BJ001',
    'Blouse Katun',
    'Blouse',
    'M',
    'Putih',
    150000,
    10
),

(
    'BJ002',
    'Dress Denim',
    'Dress',
    'L',
    'Biru',
    250000,
    5
),

(
    'BJ003',
    'Rok Katun',
    'Rok',
    'M',
    'Hitam',
    175000,
    8
)
ON CONFLICT (kode_barang) DO NOTHING;


-- ============================================================
-- RESEP PRODUKSI
-- ============================================================

INSERT INTO public.detail_produksi (id_barang, id_bahan, jumlah_digunakan)
SELECT barang.id_barang, bahan.id_bahan, resep.jumlah_digunakan
FROM (VALUES
    ('BJ001', 'BB001', 2.0),
    ('BJ001', 'BB003', 1.0),
    ('BJ001', 'BB004', 5.0),
    ('BJ002', 'BB002', 2.5),
    ('BJ002', 'BB003', 1.0),
    ('BJ002', 'BB004', 4.0),
    ('BJ003', 'BB001', 1.5),
    ('BJ003', 'BB003', 1.0),
    ('BJ003', 'BB004', 3.0)
) AS resep(kode_barang, kode_bahan, jumlah_digunakan)
JOIN public.barang_jadi AS barang ON barang.kode_barang = resep.kode_barang
JOIN public.bahan_baku AS bahan ON bahan.kode_bahan = resep.kode_bahan
ON CONFLICT (id_barang, id_bahan) DO NOTHING;


-- ============================================================
-- ROW LEVEL SECURITY
-- ============================================================

ALTER TABLE public.bahan_baku
ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.barang_jadi
ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.detail_produksi
ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.transaksi
ENABLE ROW LEVEL SECURITY;

GRANT USAGE ON SCHEMA public TO anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE
ON public.bahan_baku, public.barang_jadi, public.detail_produksi, public.transaksi
TO anon, authenticated;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated;


-- ============================================================
-- POLICY UNTUK DEMO / TUGAS
--
-- Untuk aplikasi produksi sebenarnya sebaiknya
-- menggunakan Supabase Auth.
-- ============================================================

DROP POLICY IF EXISTS "public_select_bahan" ON public.bahan_baku;
CREATE POLICY "public_select_bahan"
ON public.bahan_baku
FOR SELECT
TO anon, authenticated
USING (true);

DROP POLICY IF EXISTS "public_insert_bahan" ON public.bahan_baku;
CREATE POLICY "public_insert_bahan"
ON public.bahan_baku
FOR INSERT
TO anon, authenticated
WITH CHECK (true);

DROP POLICY IF EXISTS "public_update_bahan" ON public.bahan_baku;
CREATE POLICY "public_update_bahan"
ON public.bahan_baku
FOR UPDATE
TO anon, authenticated
USING (true)
WITH CHECK (true);

DROP POLICY IF EXISTS "public_delete_bahan" ON public.bahan_baku;
CREATE POLICY "public_delete_bahan"
ON public.bahan_baku
FOR DELETE
TO anon, authenticated
USING (true);


DROP POLICY IF EXISTS "public_select_barang" ON public.barang_jadi;
CREATE POLICY "public_select_barang"
ON public.barang_jadi
FOR SELECT
TO anon, authenticated
USING (true);

DROP POLICY IF EXISTS "public_insert_barang" ON public.barang_jadi;
CREATE POLICY "public_insert_barang"
ON public.barang_jadi
FOR INSERT
TO anon, authenticated
WITH CHECK (true);

DROP POLICY IF EXISTS "public_update_barang" ON public.barang_jadi;
CREATE POLICY "public_update_barang"
ON public.barang_jadi
FOR UPDATE
TO anon, authenticated
USING (true)
WITH CHECK (true);

DROP POLICY IF EXISTS "public_delete_barang" ON public.barang_jadi;
CREATE POLICY "public_delete_barang"
ON public.barang_jadi
FOR DELETE
TO anon, authenticated
USING (true);


DROP POLICY IF EXISTS "public_select_detail" ON public.detail_produksi;
CREATE POLICY "public_select_detail"
ON public.detail_produksi
FOR SELECT
TO anon, authenticated
USING (true);

DROP POLICY IF EXISTS "public_insert_detail" ON public.detail_produksi;
CREATE POLICY "public_insert_detail"
ON public.detail_produksi
FOR INSERT
TO anon, authenticated
WITH CHECK (true);

DROP POLICY IF EXISTS "public_update_detail" ON public.detail_produksi;
CREATE POLICY "public_update_detail"
ON public.detail_produksi
FOR UPDATE
TO anon, authenticated
USING (true)
WITH CHECK (true);

DROP POLICY IF EXISTS "public_delete_detail" ON public.detail_produksi;
CREATE POLICY "public_delete_detail"
ON public.detail_produksi
FOR DELETE
TO anon, authenticated
USING (true);


DROP POLICY IF EXISTS "public_select_transaksi" ON public.transaksi;
CREATE POLICY "public_select_transaksi"
ON public.transaksi
FOR SELECT
TO anon, authenticated
USING (true);

DROP POLICY IF EXISTS "public_insert_transaksi" ON public.transaksi;
CREATE POLICY "public_insert_transaksi"
ON public.transaksi
FOR INSERT
TO anon, authenticated
WITH CHECK (true);


-- ============================================================
-- SELESAI
-- ============================================================

NOTIFY pgrst, 'reload schema';